name: post_media_social
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.19.0-467.0.dev <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  #icon
  flutter_svg: ^1.1.6

  #font_text
  google_fonts: ^3.0.1
  # loading 
  flutter_spinkit: ^5.1.0
  #otp
  pin_code_fields: ^7.4.0

  #image
  cached_network_image: ^3.2.3

  #select file
  image_picker: ^0.8.6
  
  #object
  equatable: ^2.0.5
  http: ^0.13.5
  
  #auth phone
  firebase_core: ^2.4.0
  firebase_auth: ^4.2.2

  #state management
  flutter_bloc: ^8.1.1
  #internet checking
  connectivity_plus: ^3.0.2
  
  #depedence injection
  get_it: ^7.2.0

  json_annotation:

  dartz: ^0.10.1

  #local storage
  hive: ^2.2.3

  hive_flutter:

  #compress image file
  flutter_image_compress: ^1.1.3
  pusher_channels_flutter: ^2.1.0
  path_provider: ^2.0.11
  

dev_dependencies:

  hive_generator:

  build_runner:

  json_serializable: ^6.5.4

  flutter_launcher_icons: "^0.11.0"

  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


#icon app 
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true


  assets:
    - assets/icons/
    - assets/images/

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
